name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  deploys:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Deploy to EC2
        env:
          PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          HOST: ${{ secrets.EC2_HOST }}
          USER: ubuntu
        run: |
          echo "$PRIVATE_KEY" > private_key.pem
          chmod 600 private_key.pem

          ssh -o StrictHostKeyChecking=no -i private_key.pem $USER@$HOST << 'EOF'
            cd /home/ubuntu/fastapi

            # To pull the latest changes from the repo
            git pull origin main

            # Activate virtual environment
            source venv/bin/activate

            # Install dependencies
            pip install -r requirements.txt

            # Restart the FastAPI app
            sudo systemctl restart fastapi

            # Restart the Nginx server
              sudo systemctl restart nginx
          EOF
